// The regression harness.
//
// Every one of the 275 stock fragments must parse with zero issues. That is
// what keeps this package honest when the corpus is regenerated by the external
// pipeline: a new tag, class or attribute fails HERE, in CI, rather than in a
// customer's terminal three weeks later.

import { test } from "node:test";
import assert from "node:assert/strict";
import { readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { tokenize } from "../src/parse.ts";
import { deriveSkeleton } from "../src/skeleton.ts";
import { validateFragment } from "../src/validate.ts";

const here = dirname(fileURLToPath(import.meta.url));
const DOCS = join(here, "..", "..", "..", "content", "docs");

const files = readdirSync(DOCS).filter((f) => f.endsWith(".html"));
const read = (f: string) => readFileSync(join(DOCS, f), "utf8");
const idOf = (f: string) => f.replace(/\.html$/, "");

test("the corpus is present", () => {
  assert.ok(files.length > 200, `expected the full corpus, found ${files.length}`);
});

test("every stock fragment parses with zero issues", () => {
  const bad: string[] = [];
  for (const f of files) {
    const { issues } = tokenize(read(f));
    if (issues.length)
      bad.push(`${f}: ${issues.map((i) => `${i.rule} — ${i.message}`).join("; ")}`);
  }
  assert.deepEqual(bad, [], `\n${bad.slice(0, 20).join("\n")}`);
});

test("every stock fragment yields a usable skeleton", () => {
  const bad: string[] = [];
  for (const f of files) {
    const sk = deriveSkeleton(read(f), idOf(f));
    if (!sk.h1Text) bad.push(`${f}: no doc-title`);
    // Skeleton A (the 246 with a header band) must carry the identity rows.
    if (sk.hasHeaderband) {
      const labels = sk.headerbandRows.map((r) => r.label);
      for (const need of ["Document ID", "Title", "Version", "Effective date"])
        if (!labels.includes(need)) bad.push(`${f}: header band missing "${need}"`);
    }
  }
  assert.deepEqual(bad, [], `\n${bad.slice(0, 20).join("\n")}`);
});

test("the two skeleton shapes are both represented", () => {
  let withBand = 0;
  let withoutBand = 0;
  for (const f of files) {
    if (deriveSkeleton(read(f), idOf(f)).hasHeaderband) withBand++;
    else withoutBand++;
  }
  assert.ok(withBand > 200, `skeleton A: ${withBand}`);
  assert.ok(withoutBand > 10, `skeleton B: ${withoutBand}`);
});

// A stock fragment validated against ITSELF must report exactly the
// guidance-removal failures and nothing else. This proves no rule has an
// accidental dependency on document identity, and that a document is never
// "accidentally valid" just because it happens to be the blank.
test("identity: a blank validated as its own draft fails only on guidance", () => {
  const sample = [
    "RSK-SOP-01.html",
    "CAP-FOR-01.html",
    "AUD-LIS-01.html",
    "QMN-POL-01.html",
    "CLE-WI-01.html",
    "DEV-TPL-01.html",
  ].filter((f) => files.includes(f));
  assert.ok(sample.length >= 4, "expected the sampled documents to exist");

  for (const f of sample) {
    const html = read(f);
    const res = validateFragment({
      docId: idOf(f),
      skeleton: html,
      draft: html,
      fillMode: /-(FOR|LIS)-/.test(f) ? "scaffold" : "author",
    });
    const unexpected = res.issues
      .filter((i) => i.severity === "error")
      .filter(
        (i) =>
          !i.rule.startsWith("guidance.") &&
          !i.rule.startsWith("manual.") &&
          !i.rule.startsWith("placeholder.") &&
          !i.rule.startsWith("headerband.version") &&
          !i.rule.startsWith("headerband.no-stock") &&
          !i.rule.startsWith("headerband.effective"),
      );
    assert.deepEqual(
      unexpected.map((i) => `${i.rule}: ${i.message}`),
      [],
      `${f} produced unrelated failures`,
    );
  }
});

test("a scaffold document reports its blank as structurally intact", () => {
  const f = "CAP-FOR-01.html";
  if (!files.includes(f)) return;
  const html = read(f);
  const res = validateFragment({
    docId: idOf(f),
    skeleton: html,
    draft: html,
    fillMode: "scaffold",
  });
  const scaffoldFailures = res.issues.filter((i) => i.rule.startsWith("scaffold."));
  assert.deepEqual(
    scaffoldFailures.map((i) => i.message),
    [],
    "an untouched blank must never trip a scaffold rule",
  );
});
