"""Build deck/fonts.css from the app's own font binaries.

Why this exists
---------------
The app ships Geist and Fraunces as VARIABLE fonts (next/font/google, single
`wght` axis). Chrome renders those correctly on screen, but its PDF export
cannot embed a variable instance — it silently substitutes a system face, so a
deck printed straight from the variable files comes out in Segoe UI. Verified:
`document.fonts.check("16px Geist")` returns true and the PDF still contains
only /BaseFont /BBAAAA+SegoeUI.

So: pin the axis to fixed weights with fontTools, re-flavour to woff2, and
embed each static cut as a data URI. Same typefaces the app serves, just
instanced — no network fetch, no second-guessing which Geist we got.

    python deck/make-fonts.py
"""

import base64
import pathlib

from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

HERE = pathlib.Path(__file__).parent
MEDIA = HERE.parent / ".next" / "static" / "media"

# The latin (primary) subsets next/font emitted. Both cover €, en/em dashes and
# the punctuation the deck uses.
SOURCES = {
    "Geist": (MEDIA / "caa3a2e1cccd8315-s.p.0wgildi0cnwt9.woff2", [400, 600, 700, 800]),
    "Fraunces": (MEDIA / "03bda585a99c6450-s.p.32sris142tqlb.woff2", [600, 700, 800]),
}

OUT = HERE / "fonts.css"
STATIC_DIR = HERE / "static"
STATIC_DIR.mkdir(exist_ok=True)

css = [
    "/* Regulatory Sidekick brand fonts — the app's own Geist + Fraunces,",
    "   instanced from variable to static weights so Chrome can embed them in",
    "   the PDF, then inlined as data URIs so the deck renders with no network.",
    "   Generated by deck/make-fonts.py — do not edit by hand. */",
]

total = 0
for family, (src, weights) in SOURCES.items():
    if not src.exists():
        raise SystemExit(f"Missing {src} — run `npm run build` first to emit the fonts.")
    for w in weights:
        font = instancer.instantiateVariableFont(
            TTFont(src), {"wght": w}, inplace=False, updateFontNames=False
        )
        # instancer pins the axis; make the static weight explicit for matching.
        font["OS/2"].usWeightClass = w
        font.flavor = "woff2"
        path = STATIC_DIR / f"{family}-{w}.woff2"
        font.save(path)
        data = path.read_bytes()
        total += len(data)
        b64 = base64.b64encode(data).decode("ascii")
        css.append(
            f"@font-face{{font-family:'{family}';font-style:normal;"
            f"font-weight:{w};font-display:block;"
            f"src:url(data:font/woff2;base64,{b64}) format('woff2');}}"
        )
        print(f"  {family} {w:<4} {len(data)/1024:6.1f} KB")

OUT.write_text("\n".join(css) + "\n", encoding="utf-8")
print(f"\nwrote {OUT.name}: {OUT.stat().st_size/1024:.0f} KB "
      f"({total/1024:.0f} KB of font data across {sum(len(w) for _, w in SOURCES.values())} cuts)")
