// Derive a document's contract from its BLANK template.
//
// Everything the validator checks is a comparison against these facts, so no
// rule is hardcoded per document. That matters because the corpus is
// regenerated by an external pipeline: when a new document appears, the rules
// apply to it without anyone writing them.

import {
  tokenize,
  normalizeText,
  type Tag,
  type Token,
  type ParseIssue,
} from "./parse.ts";

export type El = {
  tag: Tag;
  attrs: Record<string, string>;
  children: Node[];
};
export type Node = El | { text: string };

export const isEl = (n: Node): n is El => "tag" in n;

export type TableFacts = {
  /** the class attribute verbatim: "grid", "grid reg", "headerband", "manual" */
  cls: string;
  /** normalized text of every cell, row by row */
  cells: string[][];
  /** cells in the first row */
  headerCells: number;
  /** rows excluding the first (which the corpus always uses as the header) */
  bodyRows: number;
  /** colspan of a td.emptyreg placeholder row, if present */
  emptyregColspan: number | null;
  /** "r1c2,r3c0" — which cells are the fill-in "[ ]" marker */
  bracketAt: string[];
};

export type SkeletonFacts = {
  docId: string;
  h1Text: string;
  hasHeaderband: boolean;
  /** left-column labels in order, plus their blank values */
  headerbandRows: { label: string; value: string }[];
  /** every h2/h3/h4 in document order, level included */
  outline: { tag: Tag; text: string }[];
  guidanceCount: number;
  manualBannerCount: number;
  manualTableCount: number;
  tables: TableFacts[];
  /** "[ ]" -> 12, "[YYYY-MM-DD]" -> 1, … */
  placeholders: Record<string, number>;
  /** whole-document normalized text, for whole-doc regex checks */
  normalizedText: string;
  /** leaf-block texts — the unit the no-invention rules diff against */
  blocks: string[];
  /** every distinct clause string found in a Clause-ish cell */
  clauses: string[];
  parseIssues: ParseIssue[];
};

/** Build a shallow element tree. The corpus never nests deeply. */
export function buildTree(tokens: Token[]): El {
  const root: El = { tag: "div", attrs: {}, children: [] };
  const stack: El[] = [root];
  for (const t of tokens) {
    const top = stack[stack.length - 1];
    if (t.k === "text") top.children.push({ text: t.text });
    else if (t.k === "void") top.children.push({ tag: t.tag, attrs: {}, children: [] });
    else if (t.k === "open") {
      const el: El = { tag: t.tag, attrs: t.attrs, children: [] };
      top.children.push(el);
      stack.push(el);
    } else if (t.k === "close") {
      if (stack.length > 1) stack.pop();
    }
  }
  return root;
}

/** Depth-first element walk. */
export function walk(el: El, fn: (e: El) => void): void {
  for (const c of el.children) {
    if (isEl(c)) {
      fn(c);
      walk(c, fn);
    }
  }
}

/** The only inline tags in the corpus — everything else separates text. */
const INLINE = new Set<Tag>(["b", "br"]);

/**
 * Normalized text of an element.
 *
 * Block boundaries MUST insert a separator: without it `<td>A</td><td>B</td>`
 * reads as "AB" and a paragraph runs into the heading after it, which both
 * invents words that were never written and breaks any comparison built on this
 * text. <b> stays glued, because it wraps parts of words.
 */
export function elText(el: El): string {
  const parts: string[] = [];
  const rec = (e: El) => {
    for (const c of e.children) {
      if (!isEl(c)) {
        parts.push(c.text);
        continue;
      }
      if (c.tag === "br") {
        parts.push(" ");
        continue;
      }
      if (INLINE.has(c.tag)) {
        rec(c);
        continue;
      }
      parts.push(" ");
      rec(c);
      parts.push(" ");
    }
  };
  rec(el);
  return normalizeText(parts.join(""));
}

/**
 * Text of every LEAF block — a paragraph, heading or cell that contains no
 * further block. This is the unit the no-invention rules compare against,
 * because it is the unit an author actually writes. Splitting a flattened
 * string on punctuation instead severs "Approved by: J. Smith" at the colon,
 * which is exactly the pattern being looked for.
 */
export function blockTexts(el: El): string[] {
  const out: string[] = [];
  const rec = (e: El) => {
    const kids = e.children.filter(isEl);
    const hasBlockChild = kids.some((c) => !INLINE.has(c.tag));
    if (!hasBlockChild) {
      const t = elText(e);
      if (t) out.push(t);
      return;
    }
    kids.forEach(rec);
  };
  el.children.filter(isEl).forEach(rec);
  return out;
}

function tableFacts(t: El): TableFacts {
  const rows: El[] = [];
  walk(t, (e) => {
    // Only rows belonging to THIS table — the corpus never nests tables, but be
    // explicit rather than relying on that.
    if (e.tag === "tr") rows.push(e);
  });

  const cells: string[][] = [];
  const bracketAt: string[] = [];
  let emptyregColspan: number | null = null;

  rows.forEach((r, ri) => {
    const row: string[] = [];
    r.children.filter(isEl).forEach((c, ci) => {
      if (c.tag !== "td" && c.tag !== "th") return;
      const text = elText(c);
      row.push(text);
      if (text === "[ ]" || text === "[]") bracketAt.push(`r${ri}c${ci}`);
      if (c.attrs.class === "emptyreg")
        emptyregColspan = Number(c.attrs.colspan ?? "0") || 0;
    });
    cells.push(row);
  });

  return {
    cls: t.attrs.class ?? "",
    cells,
    headerCells: cells[0]?.length ?? 0,
    bodyRows: Math.max(0, cells.length - 1),
    emptyregColspan,
    bracketAt,
  };
}

/** Stock placeholder tokens, counted so a filled draft can be checked for leftovers. */
export const STOCK_PLACEHOLDERS = [
  "[ ]",
  "[YYYY-MM-DD]",
  "[01]",
  "[Organisation]",
  "[role]",
  "[Role]",
  "[DOMAIN]",
  "[Y/N]",
] as const;

// A standard reference is "IEC 60601", "IEC 60601-1-2", "ISO 13485 7.3.9" — a
// number, optional -suffixes, optionally a clause number. The trailing part is
// deliberately NOT a loose character class: one that admits spaces and letters
// keeps matching past the reference and swallows the rest of the sentence, so
// "IEC 60601 Test Report - AES-FOR-01 Document ID …" is captured as a single
// "clause". That failure is invisible on a draft that copies the blank's text
// verbatim (skeleton and draft produce the same garbled string, so it is
// permitted) and fires the moment the draft deletes the guidance block — which
// every draft is required to do.
const CLAUSE_RE =
  /(?:ISO|IEC|EN)\s?\d{4,5}(?:[-–][0-9A-Za-z]+)*(?:\s+\d+(?:\.\d+)*)?|(?:MDR|IVDR)\s+Annex\s+[IVX]+[\d. ]*|21\s*CFR\s*\d+(?:\.\d+)?|GDPR\s+Art\.?\s*\d+/g;

export function deriveSkeleton(html: string, docId: string): SkeletonFacts {
  const { tokens, issues } = tokenize(html);
  const root = buildTree(tokens);

  let h1Text = "";
  let hasHeaderband = false;
  const headerbandRows: { label: string; value: string }[] = [];
  const outline: { tag: Tag; text: string }[] = [];
  const tables: TableFacts[] = [];
  let guidanceCount = 0;
  let manualBannerCount = 0;
  let manualTableCount = 0;

  walk(root, (e) => {
    const cls = e.attrs.class ?? "";
    if (e.tag === "h1" && cls === "doc-title" && !h1Text) h1Text = elText(e);
    else if (e.tag === "h2" || e.tag === "h3" || e.tag === "h4")
      outline.push({ tag: e.tag, text: elText(e) });
    else if (e.tag === "p" && cls === "guidance") guidanceCount++;
    else if (e.tag === "div" && cls === "manual-banner") manualBannerCount++;
    else if (e.tag === "table") {
      const f = tableFacts(e);
      if (cls === "manual") manualTableCount++;
      else if (cls === "headerband") {
        hasHeaderband = true;
        f.cells.forEach((r) => {
          if (r.length >= 2) headerbandRows.push({ label: r[0], value: r[1] });
        });
      } else tables.push(f);
    }
  });

  const normalizedText = elText(root);
  const blocks = blockTexts(root);

  const placeholders: Record<string, number> = {};
  for (const p of STOCK_PLACEHOLDERS) {
    const n = countOccurrences(normalizedText, p);
    if (n) placeholders[p] = n;
  }

  const clauses = [...new Set(normalizedText.match(CLAUSE_RE) ?? [])].map((c) =>
    c.trim(),
  );

  return {
    docId,
    h1Text,
    hasHeaderband,
    headerbandRows,
    outline,
    guidanceCount,
    manualBannerCount,
    manualTableCount,
    tables,
    placeholders,
    normalizedText,
    blocks,
    clauses,
    parseIssues: issues,
  };
}

export function countOccurrences(haystack: string, needle: string): number {
  if (!needle) return 0;
  let n = 0;
  let i = 0;
  for (;;) {
    const j = haystack.indexOf(needle, i);
    if (j === -1) return n;
    n++;
    i = j + needle.length;
  }
}

export { CLAUSE_RE };

/**
 * Remove the author-facing blocks every draft is required to delete.
 *
 * One definition, because there were three: the prompt renderer, the corpus
 * sweep and the test fixtures each had their own copy of these regexes, and
 * they have to agree — a document's FILL POINTS are counted after this runs,
 * so a mismatch tells an agent to replace placeholders that no longer exist.
 * 194 of 275 documents were doing exactly that for [Organisation].
 */
export function stripGuidance(html: string): string {
  return html
    .replace(/<p class="guidance">[\s\S]*?<\/p>\s*/g, "")
    .replace(/<div class="manual-banner">[\s\S]*?<\/div>\s*/g, "")
    .replace(/<table class="manual">[\s\S]*?<\/table>\s*/g, "");
}
